---
# install file for kvm
- name: Installing KVM base packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - qemu-kvm
    - qemu-utils
    - libvirt-bin

- name: Installing virt-manager
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  when: kvm_virt_manager is defined and kvm_virt_manager
  with_items:
    - virt-manager
    - xauth
